Completed javascript-modal
Johnny-Baltazar/m1-0921-code-solutions pull request #45
Opened 2021-11-10 22:43 UTC by Johnny-Baltazar

![javascript-modal](https://user-images.githubusercontent.com/25161542/141205677-d866b97a-918b-44c2-8801-9cb11bde9678.gif)

2021-11-11 20:48 UTC, Zhiwutian requested changes
functionality is approved! But I would like you to complete it without the `dialog` tag

2021-11-11 20:48 UTC, Zhiwutian commented on javascript-modal/index.html
> +    <dialog class="modal-box">
While this works, try completing the functionality without the `dialog` element using a standard div

2021-11-12 01:34 UTC, Zhiwutian approved these changes
Very nice!

2021-11-12 01:35 UTC, Johnny-Baltazar commented
![javascript-modal](https://user-images.githubusercontent.com/25161542/141393653-4e36d940-8ca5-4073-92af-ff9d1c6b4df8.gif)

2021-11-12 01:35 UTC, merged